# See https://redocly.com/docs/cli/configuration/ for more information.
apis:
  sample@v1: 
    root: openapi/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: error
features.openapi:
  showConsole: true
  htmlTemplate: ./docs/index.html
  theme:
    breakpoints: 
      medium: '9999999999px'
    overrides: 
      DownloadButton: 
        custom: 'background: red !important;'
    colors:
      primary:
        main: "#2F76D3"
    typography: 
      fontFamily: 'Source Sans Pro'
      headings: 
        fontWeight: '700'
      heading1: 
        color: 'green'
      heading2: 
        color: 'pink'
      heading3: 
        color: 'red'
      links: 
        color: '#2F76D3'
  generateCodeSamples:
    languages:  # Array of language config objects; indicates in which languages to generate code samples.
      - lang: curl
      - lang: Node.js
      - lang: JavaScript
      - lang: PHP
      - lang: Python
