openapi: 3.1.0
info:
  version: 1.0.0
  title: MyMarkit SaaS
  termsOfService: 'https://mymarkitinc.com/terms/'
  contact:
    email: contact@mymarkitinc.com
    url: 'http://mymarkitinc.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://mymarkit-production.s3.amazonaws.com/img/logos/logo-header.svg'
  description:
    $ref: ./info-description.md
tags:
  - name: Payment with Adyen
    description: Universal Payment Processor with Adyen.
  - name: Payment with Coinbase
    description: Universal Payment Processor with Coinbase Commerce.    
  - name: Webhook with Adyen 
    description: Receive payment confirmation with Adyen Webhook.    
  - name: Webhook with Coinbase 
    description: Receive payment confirmation with Coinbase Webhook  
  - name: User
    description: Operations about users.
  - name: Tag
    description: This is a tag description.

servers:
  - url: 'https://{tenant}/api/v1'
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: 'https://example.com/api/v1'
paths:
  '/users/{username}':
    $ref: 'paths/users_{username}.yaml'
  /payments:
    $ref: paths/payments.yaml
  /user-provided-url:
    $ref: paths/webhook-adyen.yaml    
  /payments/coinbase:
    $ref: paths/payments-coinbase.yaml
  /user-provided-urle:
    $ref: paths/webhook-coinbase.yaml       
  /pathItem:
    $ref: paths/path-item.yaml
  /pathItemWithExamples:
    $ref: paths/path-item-with-examples.yaml
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://example.com/api/oauth/dialog'
          scopes:
            'read:users': read users info
            'write:users': modify or remove users
    upp-api-key:
      type: apiKey
      in: header
      name: upp-api-key
    basic_auth:
      type: http
      scheme: basic
